### ISSUE TITLE
Pip cannot find package

### ISSUE THREAD

**Issue by jdmswong** [mongodb-labs/solr-doc-manager#1]
```
# pip install solr-doc-manager
Downloading/unpacking solr-doc-manager
  Could not find any downloads that satisfy the requirement solr-doc-manager
Cleaning up...
No distributions at all found for solr-doc-manager
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by ShaneHarvey** [comment]
The solr-doc-manager is bundled with the current release of mongo-connector which is 2.4.1. 
`solr-doc-manager` will be released as a separate package right before the next release of mongo-connector.

**Comment by ShaneHarvey** [comment]
Version 0.1.0 is released https://pypi.python.org/pypi/solr-doc-manager!
